# Generated by Django 4.1.3 on 2023-03-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kratos_app', '0002_remove_processor_сокет_processor_сокет'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='frequency',
            field=models.FloatField(verbose_name='Частота процессора'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='frequency',
            field=models.FloatField(verbose_name='Частота оперативной памяти'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='frequency',
            field=models.FloatField(verbose_name='Частота памяти'),
        ),
    ]
