# Generated by Django 4.1.3 on 2023-03-27 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kratos_app', '0004_motherboard_image_motherboard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboard',
            name='release_year',
            field=models.SmallIntegerField(default=2018, verbose_name='Год релиза'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ram',
            name='release_year',
            field=models.SmallIntegerField(default=2019, verbose_name='Год релиза'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocard',
            name='release_year',
            field=models.SmallIntegerField(default=2019, verbose_name='Год релиза'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='Производитель',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kratos_app.producer'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='Сокет',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kratos_app.socket'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='Тип оперативной памяти',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kratos_app.memory_type_ram'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='Форм-фактор',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kratos_app.form_factor'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='Чипсет',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kratos_app.chipset'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='Производитель',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kratos_app.producer'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='Тип оперативной памяти',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kratos_app.memory_type_ram'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='Производитель',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kratos_app.producer'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='Тип оперативной памяти',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kratos_app.memory_type_ram'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='Производитель',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kratos_app.producer'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='Тип видеопамяти',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kratos_app.memory_type_video'),
        ),
    ]
