# Generated by Django 4.1.3 on 2023-03-27 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kratos_app', '0005_motherboard_release_year_ram_release_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socket',
            old_name='name_socket',
            new_name='socket',
        ),
    ]
