# Generated by Django 4.1.3 on 2023-03-27 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kratos_app', '0008_rename_producer_producer_name_producer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processor',
            old_name='Производитель',
            new_name='name_producer',
        ),
    ]
