# Generated by Django 4.1.3 on 2023-03-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kratos_app', '0009_rename_производитель_processor_name_producer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motherboard',
            old_name='Форм-фактор',
            new_name='form_factor',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='Тип оперативной памяти',
            new_name='memory_type',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='Производитель',
            new_name='name_producer',
        ),
        migrations.RenameField(
            model_name='processor',
            old_name='Тип оперативной памяти',
            new_name='memory_type',
        ),
        migrations.RenameField(
            model_name='ram',
            old_name='Тип оперативной памяти',
            new_name='memory_type',
        ),
        migrations.RenameField(
            model_name='ram',
            old_name='Производитель',
            new_name='name_producer',
        ),
        migrations.RenameField(
            model_name='videocard',
            old_name='Тип видеопамяти',
            new_name='memory_type',
        ),
        migrations.RenameField(
            model_name='videocard',
            old_name='Производитель',
            new_name='name_producer',
        ),
    ]
