# Generated by Django 4.1.3 on 2023-03-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kratos_app', '0010_rename_форм-фактор_motherboard_form_factor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processor',
            name='Сокет',
        ),
        migrations.AddField(
            model_name='processor',
            name='name_socket',
            field=models.ManyToManyField(to='kratos_app.socket'),
        ),
    ]
