# Generated by Django 4.1.3 on 2023-03-27 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kratos_app', '0011_remove_processor_сокет_processor_name_socket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motherboard',
            name='Сокет',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='name_socket',
        ),
        migrations.DeleteModel(
            name='Socket',
        ),
    ]
