# Generated by Django 4.1.3 on 2023-03-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kratos_app', '0012_remove_motherboard_сокет_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='other',
            field=models.CharField(max_length=500, null=True, verbose_name='Остальное описание'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='other',
            field=models.CharField(max_length=500, null=True, verbose_name='Остальное описание'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='other',
            field=models.CharField(max_length=500, null=True, verbose_name='Остальное описание'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='other',
            field=models.CharField(max_length=500, null=True, verbose_name='Остальное описание'),
        ),
    ]
