# Generated by Django 4.1.3 on 2023-03-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kratos_app', '0014_alter_motherboard_other_alter_processor_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboard',
            name='price',
            field=models.SmallIntegerField(default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processor',
            name='price',
            field=models.SmallIntegerField(default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ram',
            name='price',
            field=models.SmallIntegerField(default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocard',
            name='price',
            field=models.SmallIntegerField(default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
