# Generated by Django 4.1.3 on 2023-03-27 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kratos_app', '0015_motherboard_price_processor_price_ram_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motherboard',
            old_name='Чипсет',
            new_name='chipset',
        ),
    ]
