# Generated by Django 4.1.3 on 2023-03-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kratos_app', '0016_rename_чипсет_motherboard_chipset'),
    ]

    operations = [
        migrations.AddField(
            model_name='ram',
            name='description',
            field=models.CharField(default=0, max_length=300, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocard',
            name='description',
            field=models.CharField(default=0, max_length=300, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
