# Generated by Django 4.1.3 on 2023-03-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kratos_app', '0017_ram_description_videocard_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motherboard',
            old_name='image_motherboard',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='name_motherboard',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='processor',
            old_name='image_processor',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='processor',
            old_name='name_processor',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ram',
            old_name='image_ram',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='ram',
            old_name='name_ram',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='videocard',
            old_name='image_videocard',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='videocard',
            old_name='name_videocard',
            new_name='name',
        ),
    ]
