# Generated by Django 4.1.3 on 2023-03-28 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kratos_app', '0018_rename_image_motherboard_motherboard_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('name', models.CharField(max_length=100, verbose_name='Модель процессора')),
                ('release_year', models.PositiveIntegerField(verbose_name='Год релиза')),
                ('description', models.CharField(max_length=3000, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kratos_app.category')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='chipset',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='form_factor',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='memory_type',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='name_producer',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='memory_type',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='name_producer',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='memory_type',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='name_producer',
        ),
        migrations.RemoveField(
            model_name='videocard',
            name='memory_type',
        ),
        migrations.RemoveField(
            model_name='videocard',
            name='name_producer',
        ),
        migrations.RenameField(
            model_name='producer',
            old_name='name_producer',
            new_name='producer',
        ),
        migrations.DeleteModel(
            name='Chipset',
        ),
        migrations.DeleteModel(
            name='Form_factor',
        ),
        migrations.DeleteModel(
            name='Memory_type_ram',
        ),
        migrations.DeleteModel(
            name='Memory_type_video',
        ),
        migrations.DeleteModel(
            name='Motherboard',
        ),
        migrations.DeleteModel(
            name='Processor',
        ),
        migrations.DeleteModel(
            name='Ram',
        ),
        migrations.DeleteModel(
            name='Videocard',
        ),
        migrations.AddField(
            model_name='component',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kratos_app.producer'),
        ),
    ]
