# Generated by Django 4.1.3 on 2023-03-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kratos_app', '0019_category_component_remove_motherboard_chipset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='characteristic',
            field=models.CharField(default=2342, max_length=3000, verbose_name='Характеристики'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='component',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Модель'),
        ),
    ]
